### ISSUE TITLE
Problem with Thread_SED_Coap_FreeRTOS ?

### ISSUE THREAD

**Issue by zzhang0809** [STMicroelectronics/STM32CubeWB#30]
Hello,

My dev board is STM32WB55RG and I use CubeIDE 1.6.1.

I want to implement FreeRTOS with CubeMX for my dev project based on Thread_Udp, so I choose the demo project Thread_SED_Coap_FreeRTOS as an example. But when I test the Thread_SED_Coap_FreeRTOS project on the board, it doesn't work... In detail, I can build the project with 0 error 0 warning, but when I flash it to the MCU, I can't monitor anything from my terminal. 

Therefore, I'm not sure if this is my problem or a bug.

Best regards,

**Comment by RKOUSTM** [comment]
Hi @zzhang0809,

Thank you for your report. I tried to reproduce the issue you described, but we couldn't notice the problem. I really hope you could find the root cause of this issue and, ideally, solve it.
Anyway, if you ever become able to reproduce systematically the faulty behavior and find out that the problem is related to our middleware, do not hesitate to recontact me. We could reopen this issue again.

Sorry once more for not being able to help you more than we did and wish you the best of lucks.

With regards,
