### ISSUE TITLE
STM32WB55Rx prefetch setting does not follow ioc file

### ISSUE THREAD

**Issue by fronders** [STMicroelectronics/STM32CubeWB#44]
Changing the prefetch setting in CubeMX does not change the code, only the .ioc file is changed. 

**Describe the set-up**
 * CubeMX v6.3.0 with CubeWB v1.12.1 under Windows 10 Pro x64 21H1 (build 19043.1237)

**Describe the bug**
When I disable prefetch in RCC settings from CubeMX expected behaviour is to have
```#define  PREFETCH_ENABLE              0U``` 
in stm32wbxx_hal_conf.h
But no matter what setting is selected in CubeMX it always generates the above as 
```#define  PREFETCH_ENABLE              1U``` 

P. S. I have seen this issue come up across different MCU families (most recent was G0), can you guys check all of the families at once?

**Comment by RKOUSTM** [comment]
Hi @fronders,

Thank you for your contribution. You are absolutely right about this point. Actually, the point you raised has already been dealt and fixed internally. The fix will be made available in the frame of a future release of `CubeMX` version `v6.4.0`.

Now, as this issue is not directly related to some software component published within this repository (CMSIS, HAL, BSP, etc.) but rather to our ecosystem (namely the Cube MX tool), please allow me to close it.

So stay tuned and thank you once more for your contribution and for your patience.

With regards

**Comment by RKOUSTM** [comment]
ST Internal Reference: 102660
